import type { Metadata } from "next";
import "./globals.scss";
import Header from "@/components/Header/Header";

export const metadata: Metadata = {
  title: "One Piece",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}


/* import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.scss";
import Header from "@/components/Header/Header";

const myFont = localFont({ 
  src: '/fonts/Icekingdom.ttf'  // Update the path to the public folder
});

export const metadata: Metadata = {
  title: "One Piece",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
 */