import type { Metadata } from "next";
import "./globals.scss";
import Header from "@/components/Header/Header";
import NavBar from "@/components/NavBar/NavBar";

export const metadata: Metadata = {
  title: "One Piece",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <NavBar />
        {children}
      </body>
    </html>
  );
}